const POLLING_RATE = 1000; // 1 sec
const BACKEND_GET_ENDPOINT = 'http://localhost:3001/get-capture';
const LOCAL_STORAGE_NODES_KEY = 'ethereal-canvas-nodes';
const LOCAL_STORAGE_EDGES_KEY = 'ethereal-canvas-edges';
const SIMILARITY_THRESHOLD = 2;

const MIN_OPACITY = 0.3;
const MAX_AGE_MS = 1000 * 60 * 60 * 24 * 7; // 7 days
const URL_AREA_RATIO = 0.4; // 40% of the node height

const HEADER_ONLY_HEIGHT_THRESHOLD = 50;
const BODY_ONLY_HEIGHT_THRESHOLD = 70;
const URL_HEIGHT_THRESHOLD = 300;

export {
    POLLING_RATE,
    BACKEND_GET_ENDPOINT,
    LOCAL_STORAGE_NODES_KEY,
    LOCAL_STORAGE_EDGES_KEY,
    SIMILARITY_THRESHOLD,
    MIN_OPACITY,
    MAX_AGE_MS,
    URL_AREA_RATIO,
    HEADER_ONLY_HEIGHT_THRESHOLD,
    BODY_ONLY_HEIGHT_THRESHOLD,
    URL_HEIGHT_THRESHOLD
}